### PR TITLE
Scrolling Options

### PR DESCRIPTION
**Pull request by a-kenji**
Hey! This PR introduces more Scrolling Options, namely:
big_up = [ "K" ]
big_down = [ "L" ]
page_up = [ "PgUp" ]
page_down = [ "PgDn" ]
go_top = [ "g" ]
go_bot = [ "G" ]

Big Up and Big Down depend on BIG_SCROLL_AMOUNT: i32 = 4 and the screen size.

Sadly I couldn't run rustfmt with the options in rustfmt.toml, so I refrained from doing so atm.
I will try to figure out what is going wrong with my rusftmt in the meantime.

### CODE REVIEW

**Comment by jeff-hughes** [comment]
Awesome! I have only had a quick look at this, I want to do some additional testing, but this looks really good!

In terms of rustfmt, unfortunately a lot of their features are still locked behind Rust nightly ([see here for the list of config options](https://rust-lang.github.io/rustfmt/?version=master&search=)). The project itself is built on stable Rust, but to get rustfmt working with everything I wanted, I had to add the nightly toolchain and then run it with `cargo +nightly fmt`. I'm really hoping that they push more of these features onto stable, but for now that's how I have things set up...

**Comment by a-kenji** [comment]
Thanks for the help! I'll try it out on nightly.

**Comment by jeff-hughes** [comment]
Sorry for the delay, but after doing some testing, I think it looks great. I just changed the keybinding for `big_down` to `J` instead of `L` -- I suspect that was just a typo, but either way, I think it's better if it's consistent with the keybinding for `down`. Other than that, looks great. I'll merge in just a second. Thanks as always for the contributions!

**Comment by a-kenji** [comment]
Yes, good catch! That was a typo. I didn't notice it because I was overwriting it with a local config file. Cheers!

**Pull request merged**
